--LAB-13--

--VIEWS--

CREATE TABLE STUDENT_1
(RNO INT,
 NAME VARCHAR(50),
 BRANCH VARCHAR(50),
 SPI DECIMAL(4,2),
 BKLOG INT
 );

 INSERT INTO STUDENT_1 VALUES(101,'RAJU','CE',8.80,0),
                             (102,'AMIT','CE',2.20,3),
							 (103,'SANJAY','ME',1.50,6),
							 (104,'NEHA','EC',7.65,1),
							 (105,'MEERA','EE',5.52,2),
							 (106,'MAHESH','EC',4.50,3)

SELECT * FROM STUDENT_1


--1--

CREATE VIEW PERSONAL
AS SELECT * FROM STUDENT_1

SELECT * FROM PERSONAL

--2--

CREATE VIEW STUDENT_DETAILS
AS SELECT NAME,BRANCH,SPI FROM STUDENT_1

SELECT * FROM STUDENT_DETAILS

--3--

CREATE VIEW ACADEMIC
AS SELECT RNO,NAME,BRANCH FROM STUDENT_1

SELECT * FROM ACADEMIC

--4--

CREATE VIEW STUDENT_DATA
AS SELECT * FROM STUDENT_1
WHERE BKLOG>2

SELECT * FROM STUDENT_DATA

--5--

CREATE VIEW STUDENT_PATTERN
AS SELECT RNO,NAME,BRANCH FROM STUDENT_1
WHERE NAME LIKE '____'

SELECT * FROM STUDENT_PATTERN

--6--

SELECT * FROM ACADEMIC

INSERT INTO ACADEMIC VALUES(107,'MEET','ME')

SELECT * FROM ACADEMIC

--7--

SELECT * FROM STUDENT_1

UPDATE STUDENT_DETAILS
SET BRANCH='ME'
WHERE NAME='AMIT'

SELECT * FROM STUDENT_DETAILS

SELECT * FROM STUDENT_1

--8--

DELETE FROM ACADEMIC
WHERE RNO=104

SELECT * FROM ACADEMIC

SELECT * FROM STUDENT_1

--9--

CREATE VIEW STUDENT_DEMO
AS SELECT * FROM STUDENT_1
WHERE SPI>9.5

SELECT * FROM STUDENT_DEMO

--10--

CREATE VIEW STUDENT_LIST
AS SELECT * FROM STUDENT_1
WHERE BKLOG=0

SELECT * FROM STUDENT_LIST




							   