--Lab - 9--

--SET OPERATORS--

CREATE TABLE COMPUTER
(ROLLNO INT,
 NAME VARCHAR(50)
 );

 INSERT INTO COMPUTER VALUES (101,'AJAY'),
                             (109,'HARESH'),
                              (115,'MANISH')

CREATE TABLE ELECTRICAL
(ROLLNO INT,
 NAME VARCHAR(50)
 );

  INSERT INTO ELECTRICAL VALUES (105,'AJAY'),
                             (107,'MAHESH'),
                              (115,'MANISH')

SELECT * FROM COMPUTER
SELECT * FROM ELECTRICAL

SELECT NAME FROM COMPUTER
UNION
SELECT NAME FROM ELECTRICAL

SELECT NAME FROM COMPUTER
UNION ALL
SELECT NAME FROM ELECTRICAL

SELECT NAME FROM COMPUTER
INTERSECT
SELECT NAME FROM ELECTRICAL

SELECT NAME FROM COMPUTER
EXCEPT
SELECT NAME FROM ELECTRICAL

SELECT NAME FROM ELECTRICAL
EXCEPT
SELECT NAME FROM COMPUTER

SELECT * FROM COMPUTER
UNION 
SELECT * FROM ELECTRICAL

SELECT * FROM COMPUTER
INTERSECT
SELECT * FROM ELECTRICAL


--INTO--

CREATE TABLE CRICKET
(NAME VARCHAR(50),
 CITY VARCHAR(50),
 AGE INT);

 INSERT INTO CRICKET VALUES('SACHIN TENDULKAR','MUMBAI',30),
                           ('RAHUL DRAVID','BOMBAY',35),
						   ('M.S.DHONI','JHARKHAND',31),
						   ('SURESH RAINA','GUJARAT',30)
						   
SELECT * FROM CRICKET

SELECT * INTO WORLDCUP FROM CRICKET	

SELECT * FROM WORLDCUP

SELECT NAME,CITY INTO T20 FROM CRICKET 
WHERE 1=2;

SELECT * FROM T20 

SELECT * INTO IPL FROM CRICKET
WHERE 1=2;

SELECT * FROM IPL

INSERT INTO IPL SELECT * FROM CRICKET
WHERE NAME LIKE '_A_____%'

SELECT * FROM IPL

DELETE FROM IPL

DELETE FROM CRICKET
WHERE CITY='JHARKHAND'

SELECT * FROM CRICKET

SP_RENAME 'IPL' , 'IPL2018'

SELECT * FROM IPL2018

DROP TABLE T20


     					    






